// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, user_id, filename, file_type)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, filename, file_type, uploaded_at
`

type CreateDocumentParams struct {
	ID       string      `json:"id"`
	UserID   string      `json:"user_id"`
	Filename pgtype.Text `json:"filename"`
	FileType pgtype.Text `json:"file_type"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.FileType,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.FileType,
		&i.UploadedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, user_id, filename, file_type, uploaded_at FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.FileType,
		&i.UploadedAt,
	)
	return i, err
}

const listDocumentsByUser = `-- name: ListDocumentsByUser :many
SELECT id, user_id, filename, file_type, uploaded_at FROM documents
WHERE user_id = $1
ORDER BY uploaded_at DESC LIMIT $1 OFFSET $2
`

type ListDocumentsByUserParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDocumentsByUser(ctx context.Context, arg ListDocumentsByUserParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.FileType,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentFilename = `-- name: UpdateDocumentFilename :exec
UPDATE documents
SET filename = $2
WHERE id = $1
`

type UpdateDocumentFilenameParams struct {
	ID       string      `json:"id"`
	Filename pgtype.Text `json:"filename"`
}

func (q *Queries) UpdateDocumentFilename(ctx context.Context, arg UpdateDocumentFilenameParams) error {
	_, err := q.db.Exec(ctx, updateDocumentFilename, arg.ID, arg.Filename)
	return err
}
