// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: extracted_text.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExtractedText = `-- name: CreateExtractedText :one
INSERT INTO extracted_texts (id, document_id, content)
VALUES ($1, $2, $3)
RETURNING id, document_id, content, created_at
`

type CreateExtractedTextParams struct {
	ID         string      `json:"id"`
	DocumentID string      `json:"document_id"`
	Content    pgtype.Text `json:"content"`
}

func (q *Queries) CreateExtractedText(ctx context.Context, arg CreateExtractedTextParams) (ExtractedText, error) {
	row := q.db.QueryRow(ctx, createExtractedText, arg.ID, arg.DocumentID, arg.Content)
	var i ExtractedText
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExtractedText = `-- name: DeleteExtractedText :exec
DELETE FROM extracted_texts
WHERE id = $1
`

func (q *Queries) DeleteExtractedText(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteExtractedText, id)
	return err
}

const getExtractedTextByID = `-- name: GetExtractedTextByID :one
SELECT id, document_id, content, created_at FROM extracted_texts
WHERE id = $1
`

func (q *Queries) GetExtractedTextByID(ctx context.Context, id string) (ExtractedText, error) {
	row := q.db.QueryRow(ctx, getExtractedTextByID, id)
	var i ExtractedText
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listExtractedTextsByDocument = `-- name: ListExtractedTextsByDocument :many
SELECT id, document_id, content, created_at FROM extracted_texts
WHERE document_id = $1
ORDER BY created_at DESC  LIMIT $1 OFFSET $2
`

type ListExtractedTextsByDocumentParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListExtractedTextsByDocument(ctx context.Context, arg ListExtractedTextsByDocumentParams) ([]ExtractedText, error) {
	rows, err := q.db.Query(ctx, listExtractedTextsByDocument, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExtractedText
	for rows.Next() {
		var i ExtractedText
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExtractedTextContent = `-- name: UpdateExtractedTextContent :exec
UPDATE extracted_texts
SET content = $2
WHERE id = $1
`

type UpdateExtractedTextContentParams struct {
	ID      string      `json:"id"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) UpdateExtractedTextContent(ctx context.Context, arg UpdateExtractedTextContentParams) error {
	_, err := q.db.Exec(ctx, updateExtractedTextContent, arg.ID, arg.Content)
	return err
}
