// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID         string           `json:"id"`
	UserID     string           `json:"user_id"`
	Filename   pgtype.Text      `json:"filename"`
	FileType   pgtype.Text      `json:"file_type"`
	UploadedAt pgtype.Timestamp `json:"uploaded_at"`
}

type ExtractedText struct {
	ID         string           `json:"id"`
	DocumentID string           `json:"document_id"`
	Content    pgtype.Text      `json:"content"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID      `json:"id"`
	Username     string           `json:"username"`
	RefreshToken string           `json:"refresh_token"`
	UserAgent    string           `json:"user_agent"`
	ClientIp     string           `json:"client_ip"`
	IsBlocked    bool             `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type User struct {
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	Provider     pgtype.Text      `json:"provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
